### ISSUE TITLE
打包一EXE

### ISSUE THREAD

**Issue by SONGjiemo** [iminto/hideImage#2]
打包一EXE吧

**Comment by iminto** [comment]
必要性不大，这个app依赖JDK，打包体积会很大。不过，如果使用JDK9+的模块化，打包体积能缩小到40-50M左右。

参考命令
`jlink -p $JAVA_HOME/jmods -p e:/data/project/hideImage/jmods --add-modules java.base,java.desktop,java.logging,hide --launcher HideImage=hide --output jre `
